USE [master]
GO
/****** Object:  Database [CHALLENGEDB]    Script Date: 06/12/2021 13:54:10 ******/
CREATE DATABASE [CHALLENGEDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CHALLENGEDB', FILENAME = N'/var/opt/mssql/data/CHALLENGEDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CHALLENGEDB_log', FILENAME = N'/var/opt/mssql/data/CHALLENGEDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CHALLENGEDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHALLENGEDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CHALLENGEDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CHALLENGEDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CHALLENGEDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CHALLENGEDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CHALLENGEDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET RECOVERY FULL 
GO
ALTER DATABASE [CHALLENGEDB] SET  MULTI_USER 
GO
ALTER DATABASE [CHALLENGEDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CHALLENGEDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CHALLENGEDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CHALLENGEDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CHALLENGEDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CHALLENGEDB', N'ON'
GO
ALTER DATABASE [CHALLENGEDB] SET QUERY_STORE = OFF
GO
USE [CHALLENGEDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[UserName] [varchar](100) NOT NULL,
	[Email] [varchar](150) NOT NULL,
	[Password] [nvarchar](1000) NOT NULL,
	[Salt] [nvarchar](1000) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AccountToken](
	[AccountId] [uniqueidentifier] NOT NULL,
	[Token] [uniqueidentifier] NOT NULL,
	[RefreshToken] [uniqueidentifier] NULL,
	[TokenExpiration] [datetime] NOT NULL,
	[RefreshExpiration] [datetime] NULL,
 CONSTRAINT [PK_AccountToken] PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC,
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Portfolio](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[AccountId] [uniqueidentifier] NOT NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NULL,
 CONSTRAINT [PK_Portfolio] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trade](
	[Id] [uniqueidentifier] NOT NULL,
	[Date] [datetime] NOT NULL,
	[Executor] [uniqueidentifier] NOT NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NULL,
	[PortfolioId] [uniqueidentifier] NOT NULL,
	[Shares] [int] NOT NULL,
	[Price] [decimal](18, 0) NOT NULL,
	[Currency] [varchar](3) NOT NULL,
	[MarketValue] [decimal](18, 0) NOT NULL,
	[Action] [varchar](30) NOT NULL,
	[Note] [varchar](50) NULL,
	[Asset] [varchar](10) NULL,
 CONSTRAINT [PK_Trade] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AccountToken]  WITH CHECK ADD  CONSTRAINT [FK_AccountToken_Account] FOREIGN KEY([AccountId])
REFERENCES [dbo].[Account] ([Id])
GO
ALTER TABLE [dbo].[AccountToken] CHECK CONSTRAINT [FK_AccountToken_Account]
GO
ALTER TABLE [dbo].[Portfolio]  WITH CHECK ADD  CONSTRAINT [FK_Portfolio_Account] FOREIGN KEY([AccountId])
REFERENCES [dbo].[Account] ([Id])
GO
ALTER TABLE [dbo].[Portfolio] CHECK CONSTRAINT [FK_Portfolio_Account]
GO
ALTER TABLE [dbo].[Trade]  WITH CHECK ADD  CONSTRAINT [FK_Trade_Portfolio] FOREIGN KEY([PortfolioId])
REFERENCES [dbo].[Portfolio] ([Id])
GO
ALTER TABLE [dbo].[Trade] CHECK CONSTRAINT [FK_Trade_Portfolio]
GO
USE [master]
GO
ALTER DATABASE [CHALLENGEDB] SET  READ_WRITE 
GO